locals {
  common_labels = merge(var.labels, {
    managed_by = "terraform"
    cluster    = var.cluster_name
    platform   = "monitoring"
  })
}

module "network" {
  source = "./modules/network"

  cluster_name = var.cluster_name
  network_cidr = var.network_cidr
  subnet_cidr  = var.subnet_cidr
  network_zone = var.network_zone
  labels       = local.common_labels
}

module "firewall" {
  source = "./modules/firewall"

  cluster_name      = var.cluster_name
  network_cidr      = var.network_cidr
  ssh_allowed_cidrs = var.ssh_allowed_cidrs
  api_allowed_cidrs = var.api_allowed_cidrs
  labels            = local.common_labels
}

resource "hcloud_load_balancer" "api" {
  name               = "${var.cluster_name}-api-lb"
  load_balancer_type = var.lb_type
  location           = var.region
  labels             = local.common_labels
}

resource "hcloud_load_balancer_network" "api" {
  load_balancer_id = hcloud_load_balancer.api.id
  network_id       = module.network.network_id
}

resource "hcloud_load_balancer_service" "kube_api" {
  load_balancer_id = hcloud_load_balancer.api.id
  protocol         = "tcp"
  listen_port      = 6443
  destination_port = 6443

  health_check {
    protocol = "tcp"
    port     = 6443
    interval = 10
    timeout  = 5
    retries  = 3
  }
}

resource "hcloud_load_balancer_service" "k3s_supervisor" {
  load_balancer_id = hcloud_load_balancer.api.id
  protocol         = "tcp"
  listen_port      = 9345
  destination_port = 9345

  health_check {
    protocol = "tcp"
    port     = 9345
    interval = 10
    timeout  = 5
    retries  = 3
  }
}

module "servers" {
  source = "./modules/server"

  cluster_name = var.cluster_name
  location     = var.region
  hcloud_token = var.hcloud_token

  network_id = module.network.network_id
  subnet_id  = module.network.subnet_id

  control_plane_server_type     = var.control_plane_type
  control_plane_image           = var.control_plane_image
  control_plane_firewall_id     = module.firewall.control_plane_firewall_id
  cloud_init_control_plane_path = "${path.module}/cloud-init/control-plane.yaml.tftpl"

  worker_count           = var.node_count
  worker_server_type     = var.node_type
  worker_image           = var.worker_image
  worker_firewall_id     = module.firewall.worker_firewall_id
  cloud_init_worker_path = "${path.module}/cloud-init/worker.yaml.tftpl"

  k3s_version      = var.k3s_version
  k3s_token        = var.k3s_token
  api_server_lb_ip = hcloud_load_balancer.api.ipv4
  pod_cidr         = var.pod_cidr
  service_cidr     = var.service_cidr
  cluster_dns      = var.cluster_dns

  ssh_public_key_path = var.ssh_public_key_path

  labels = local.common_labels
}

resource "hcloud_load_balancer_target" "control_plane" {
  load_balancer_id = hcloud_load_balancer.api.id
  type             = "server"
  server_id        = module.servers.control_plane_id
  use_private_ip   = true
}

resource "null_resource" "kubeconfig" {
  triggers = {
    control_plane_id = module.servers.control_plane_id
    api_lb_ip        = hcloud_load_balancer.api.ipv4
  }

  provisioner "local-exec" {
    command = <<-EOT
      set -euo pipefail
      SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5"
      SSH_KEY="${pathexpand(var.ssh_private_key_path)}"
      SSH_HOST="root@${module.servers.control_plane_ip}"

      for i in $(seq 1 60); do
        if ssh $SSH_OPTS -i "$SSH_KEY" "$SSH_HOST" 'test -f /etc/rancher/k3s/k3s.yaml' 2>/dev/null; then
          break
        fi
        if [ "$i" -eq 60 ]; then
          echo "kubeconfig was not generated by k3s in time."
          exit 1
        fi
        sleep 10
      done

      ssh $SSH_OPTS -i "$SSH_KEY" "$SSH_HOST" 'cat /etc/rancher/k3s/k3s.yaml' \
        | sed 's|https://127.0.0.1:6443|https://${hcloud_load_balancer.api.ipv4}:6443|g' \
        > ${path.module}/../kubeconfig.yaml
      chmod 600 ${path.module}/../kubeconfig.yaml
    EOT
  }

  depends_on = [hcloud_load_balancer_target.control_plane]
}
