variable "hcloud_token" {
  description = "Hetzner Cloud API token"
  type        = string
  sensitive   = true
}

variable "cluster_name" {
  description = "Name prefix for all cluster resources"
  type        = string
  default     = "monitoring-k3s"
}

variable "region" {
  description = "Hetzner datacenter location (nbg1, fsn1, hel1, ash, hil)"
  type        = string
  default     = "nbg1"
}

variable "node_type" {
  description = "Hetzner server type for worker nodes"
  type        = string
  default     = "cpx31"
}

variable "node_count" {
  description = "Number of worker nodes"
  type        = number
  default     = 2

  validation {
    condition     = var.node_count >= 1 && var.node_count <= 20
    error_message = "node_count must be between 1 and 20."
  }
}

variable "control_plane_type" {
  description = "Hetzner server type for control plane node"
  type        = string
  default     = "cpx31"
}

variable "network_zone" {
  description = "Hetzner network zone"
  type        = string
  default     = "eu-central"
}

variable "network_cidr" {
  description = "CIDR for private cluster network"
  type        = string
  default     = "10.0.0.0/8"
}

variable "subnet_cidr" {
  description = "CIDR for private cluster subnet"
  type        = string
  default     = "10.0.0.0/16"
}

variable "control_plane_image" {
  description = "OS image for control plane node"
  type        = string
  default     = "ubuntu-24.04"
}

variable "worker_image" {
  description = "OS image for worker nodes"
  type        = string
  default     = "ubuntu-24.04"
}

variable "k3s_version" {
  description = "k3s version to install"
  type        = string
  default     = "v1.30.2+k3s1"
}

variable "k3s_token" {
  description = "Shared token for k3s cluster join. If empty, token is autogenerated."
  type        = string
  default     = ""
  sensitive   = true
}

variable "pod_cidr" {
  description = "Kubernetes pod CIDR"
  type        = string
  default     = "10.42.0.0/16"
}

variable "service_cidr" {
  description = "Kubernetes service CIDR"
  type        = string
  default     = "10.43.0.0/16"
}

variable "cluster_dns" {
  description = "Cluster DNS service IP"
  type        = string
  default     = "10.43.0.10"
}

variable "ssh_public_key_path" {
  description = "Path to SSH public key"
  type        = string
  default     = "~/.ssh/id_ed25519.pub"
}

variable "ssh_private_key_path" {
  description = "Path to SSH private key"
  type        = string
  default     = "~/.ssh/id_ed25519"
}

variable "lb_type" {
  description = "Hetzner Load Balancer type for API server"
  type        = string
  default     = "lb11"
}

variable "ssh_allowed_cidrs" {
  description = "CIDR blocks allowed to SSH into nodes"
  type        = list(string)
  default     = ["0.0.0.0/0", "::/0"]
}

variable "api_allowed_cidrs" {
  description = "CIDR blocks allowed to access Kubernetes API"
  type        = list(string)
  default     = ["0.0.0.0/0", "::/0"]
}

variable "labels" {
  description = "Additional labels to apply to resources"
  type        = map(string)
  default     = {}
}
