apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: default
      group_by: ["alertname", "cluster", "namespace"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - receiver: critical
          matchers:
            - severity="critical"
        - receiver: warning
          matchers:
            - severity="warning"
    receivers:
      - name: default
      - name: warning
      - name: critical
