config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

  snippets:
    pipelineStages:
      - cri: {}
      - labeldrop:
          - filename
          - stream

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

serviceMonitor:
  enabled: true
  namespace: monitoring
