apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-remote-loki-example
  namespace: monitoring
data:
  values-promtail-remote.yaml: |
    config:
      clients:
        - url: https://${LOKI_HOST}/loki/api/v1/push
          external_labels:
            cluster: ${PROD_CLUSTER_NAME}
            env: ${PROD_ENV}
      snippets:
        pipelineStages:
          - cri: {}
          - json:
              expressions:
                level: level
                msg: message
    serviceMonitor:
      enabled: true
